service: aws-dynamodb-consumed-metrics-operator



provider:
  name: aws
  runtime: python3.6

functions:
  run:
    handler: handler.run
    environment:
      THRESHOLD_VALUE: 0.5
      THRESHOLD_TIME: 5